### ISSUE TITLE
Why GROUP BY vcf_line in SQL requests?

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/Regovar#46]
To select *de novo* variants.
``` sql
DROP TABLE IF EXISTS wt_7_tmp CASCADE;
  CREATE TABLE wt_7_tmp AS
  SELECT
    ROW_NUMBER() OVER(ORDER BY vcf_line) as page,
    variant_id,
    array_remove(array_agg(trx_pk_value), NULL) as trx,
    count(trx_pk_value) as trx_count,
    vcf_line
  FROM wt_7
  WHERE (is_denovo=true)
  GROUP BY variant_id, vcf_line;
```
One can have the same vcf line in different files and vcf_line doesn't account for this.

**Comment by ikit** [comment]
The DROP/CREATION wt_X_tmp table is done during the "prepare" phase. This phase occure each time you press the "apply filter" button. The goal is to create a temporary table with the result of the result of the filter according the sort options. 
The wt_X_tm temps table shall contains only variants id and for each variant, how many transcript count. That's why there is a "group by variant_id" with "count" aggregation method in the query.

But if you set a special ordering, we need to sort variants on the specific field, and to be able to do that, I have to add the field also in the group by instruction. So here, in your example, if you see the "vcfline" in the query, it's because you was sorting the table on the vcf_line column.

But as we are first grouping by variant_id which is the most "stringent", the second group_by field should never impact the result of the query.
